CREATE TABLE [dbo].[Chitti] (

	ChittiPID BIGINT IDENTITY(1,1) NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Amount MONEY NOT NULL,
	Commission MONEY NOT NULL,
	NoOfMonths INT NOT NULL,
	StartDate DATE NOT NULL,
	CreatedON DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedOn DATETIME NULL,
	CreatedBy BIGINT NOT NULL,
	UpdatedBy BIGINT NULL
)

GO

--PK_Chitti
ALTER TABLE [dbo].[Chitti]
	ADD CONSTRAINT [PK_Chitti] PRIMARY KEY CLUSTERED ([ChittiPID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY= OFF, STATISTICS_NORECOMPUTE = OFF)

GO
