CREATE TABLE [dbo].[People] (

	PeoplePID BIGINT IDENTITY(1,1) NOT NULL,
	Name varchar(50) NOT NULL,
	PhoneNumber BIGINT NOT NULL,
	ChittiPID BIGINT NOT NULL,
	CreatedON DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedOn DATETIME NULL,
	CreatedBy BIGINT NOT NULL,
	UpdatedBy BIGINT NULL
)

GO

--PK_People
ALTER TABLE [dbo].[People]
	ADD CONSTRAINT [PK_People] PRIMARY KEY CLUSTERED ([People] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY= OFF, STATISTICS_NORECOMPUTE = OFF)

GO

	
--FK_People_Chitti
ALTER TABLE [dbo].[People]
	ADD CONSTRAINT [FK_People_Chitti] FOREIGN KEY ([ChittiPID]) REFERENCES [dbo].[Chitti]([ChittiPID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

GO

