CREATE TABLE [dbo].[Permission] (

	PermissionPID BIGINT IDENTITY(1,1) NOT NULL,
	ChittiPID BIGINT NOT NULL,
	UserPID BIGINT NOT NULL,
	RolePID BIGINT NOT NULL,	
	CreatedON DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedOn DATETIME NULL,
	CreatedBy BIGINT NOT NULL,
	UpdatedBy BIGINT NULL
)

GO

--PK_Permission
ALTER TABLE [dbo].[Permission]
	ADD CONSTRAINT [PK_Permission] PRIMARY KEY CLUSTERED ([Permission] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY= OFF, STATISTICS_NORECOMPUTE = OFF)

GO

	
--FK_Permission_Chitti
ALTER TABLE [dbo].[Permission]
	ADD CONSTRAINT [FK_Permission_Chitti] FOREIGN KEY ([ChittiPID]) REFERENCES [dbo].[Chitti]([ChittiPID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

GO

--FK_Permission_NotificationType
ALTER TABLE [dbo].[Permission]
	ADD CONSTRAINT [FK_Permission_Role] FOREIGN KEY ([RolePID]) REFERENCES [dbo].[Role]([RolePID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

GO
